### ISSUE TITLE
 build failure

### ISSUE THREAD

**Issue by wanghaisheng** [ysc/cws_evaluation#1]
ubuntu  jdk1.8
according to https://github.com/NLPchina/ansj_seg,  
replace    ansj_seg maven repo to    

```
  <repository>
            <id>mvn-repo</id>
            <url>http://maven.nlpcn.org/org/ansj</url>
  </repository>
```

then run 
 chmod +x contrast.sh & ./contrast.sh

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.681 s
[INFO] Finished at: 2015-12-11T14:55:09+08:00
[INFO] Final Memory: 41M/3925M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cws_evaluation: Could not resolve dependencies for project org.apdplat:cws_evaluation:jar:1.1: Could not find artifact org.ansj:ansj_seg:jar:3.0 in lib_id (file:///home/edwin-clear/resources/workspace/cws_evaluation/lib) -> [Help 1]

**Comment by ysc** [comment]
drop the path "/org/ansj" :

```
  <repository>
        <id>mvn-repo</id>
        <url>http://maven.nlpcn.org</url>
  </repository>
```
